Implement push. This is still pretty rough and needs a lot of cleaning up. Currently filecopy (local fs->local fs), pull (remote->local fs) and push (local fs -> remote) work. The backup_jobs syntax is incompatible with the old configurations and they need to be adjusted to contain destination and paths for source and destination. The destination path supports some variable expansion like %origin% -> source machine of the backups.
Mark tools/create_DBs as broken, it doesn't support the new backup
directory syntax.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -24,7 +24,6 @@
 ####################################
 
 # defaults, the same as in backup.conf.sample
-backups=/backups
 min_backups=3
 max_backups=250
 mailto="root"
@@ -37,6 +36,10 @@ backup_jobs=
 # Other variables.
 task_count=0
 task_successes=0
+
+# default settings
+# XXX: -e
+set -u
 
 # default umask
 umask 077
@@ -61,15 +64,19 @@ fi
 . "$BASE/config/backup.conf"
 
 # Call function to to check tool requirements.
-required_tools="rm ls date df kill ping mail tr ssh find dirname basename
-tail sort head install wc du bc cut awk uname whoami pgrep rsync"
-check_required_tools
+check_required_tools rm ls date df kill ping mail tr ssh find \
+	dirname basename tail sort head install wc du bc cut awk \
+	uname whoami pgrep rsync
+
+date=$(date +%Y-%m-%d-%H)
 
 # Check that there aren't other processes running
 check_backup_process
 
 # Call function to parse command line arguments.
-parse_arguments $@
+if [ "$#" -gt 0 ]; then
+	parse_arguments $@
+fi
 
 # Call function to install signal traps and init other stuff.
 run_init
@@ -79,73 +86,69 @@ check_configured_jobs
 
 backup_loop()
 {
-
-	local ssh_verbose; ssh_verbose=
-	if [ "$debug" = 'YES' ]; then
-		ssh_verbose='-vv'
-	fi
-
-	local socket
-	local sockets; sockets=
+	local ret
 	local tmp_filter_file
+	local backup_mode
 	for backup_job in $parsed_jobs; do
-	
-		# Get _target, _user, _host and _login
+		# Explode backup job into usable variables.
 		parse_target "$backup_job"
 
-		filter_name=$(echo "$backup_job" | cut -f 4 -d ':')
-
-		if [ "$_host" != "localhost" ]; then
-			ping -w 1 -c 1 "${_host}" 1>/dev/null 2>/dev/null
-			if [ "$?" -ne 0 ]; then
-				printf '%s\n' "[SKIPPING] \"$_host\" is currently unavailable" | log
-				continue 1
-			fi
-		fi
+		# Skip ping test if both are defined as localhost.
+		# Relay doesn't work with rsync, so only localhost<->localhost is valid
+		# because we handle it specially.
+		case "$backup_mode" in
+		relay)
+			echo "Error in configuration: rsync doesn't support relay." | log
+			continue
+			;;
+		push) pingtest "$_dst_host" ;;
+		pull) pingtest "$_src_host" ;;
+		esac
 
 		printf '%s\n' "Truncating filter file" | debuglog
 		tmp_filter_file="$TMPDIR/tempfiles/filter"
-		echo -n '' > "$tmp_filter_file"
+		: > "$tmp_filter_file"
 
 		task_count=$((task_count + 1))
-		printf '%s\n' "\"$_host\" is alive" | log
 
 		# Check for incomplete installation.
-		check_ssh_keyfile "$_host"
-		if [ "$?" -ne 0 ]; then
-			printf '%s\n' "[SKIPPING] You don't have host key set. \"ssh ${_host}\" and accept signature." | log
-			continue
-		fi
-
-		# Check for existing socket
-		socket="${TMPDIR}/sockets/$_login"
-		echo "$sockets" | fgrep -q -w -e "$_login"
-		if [ "$?" -ne 0 ] && [ "$_host" != "localhost" ]; then
-			# Open a connection to the remote host and
-			# create a control socket
-			# ssh -S /tmp/ssh_socket -M -N -f host.example.com
-			ssh \
+		local generic_filter=
+		case "$backup_mode" in
+		filecopy)
+			last_backup_dir=$(\
+				find "$_dst_dir" -maxdepth 1 | \
+				egrep -e '/[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}$' | \
+				sort -n | tail -n 1)
+			generic_filter="generic:${_src_login}"
+			;;
+		push)
+			check_ssh_keyfile "$_dst_user" "$_dst_host" || continue
+			setup_socket "$_dst_login"
+			last_backup_dir=$(ssh \
 				-S "$socket" \
-				-M \
-				-N \
 				-o PasswordAuthentication=no \
 				-o BatchMode=yes \
-				-i "$ssh_key" \
-				-f "$_login" 2>&1 | debuglog
-			if [ "$?" -ne 0 ]; then
-				printf '%s\n' "[SKIPPING] failed to create ssh master socket for $_login" | log
-				continue
-			fi
-			sockets="$sockets $_login"
-			printf '%s\n' "Created socket for \"$_login\"" | debuglog
-		fi
+				"$_dst_login" \
+				"find '${_dst_dir}' -type d -maxdepth 1 | \
+				egrep -e '/[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}$' | \
+				sort -n | tail -n 1")
+			generic_filter="generic:${_dst_login}"
+			rsync_src=${_src_dir}
+			rsync_dst="${_dst_login}:${_dst_dir}/${date}"
+			;;
+		pull)
+			check_ssh_keyfile "$_src_user" "$_src_host" || continue
+			setup_socket "$_src_login"
+			last_backup_dir=$(\
+				find "$_dst_dir" -maxdepth 1 | \
+				egrep -e '/[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}$' | \
+				sort -n | tail -n 1)
+			generic_filter="generic:${_src_login}"
+			rsync_src="${_src_login}:${_src_dir}"
+			rsync_dst="${_dst_dir}/${date}"
+			;;
+		esac
 
-		last_backup_dir=$(find "${backups}/${_login}/${filter_name}/" \
-			-maxdepth 1 \
-			-name "????-??-??-??" | sort -n | tail -n 1)
-
-		date=$(date +%Y-%m-%d-%H)
-		new_dir="${backups}/${_login}/${filter_name}/${date}"
 
 		# Previous backup found -> use it as base.
 		local rsync_last_backup_dir; rsync_last_backup_dir=
@@ -153,15 +156,16 @@ backup_loop()
 			rsync_last_backup_dir="--link-dest=$last_backup_dir"
 		fi
 
-		if [ ! -f "${BASE}/config/filters/${filter_name}" ]; then
+		if [ ! -f "${BASE}/config/filters/${_filter}" ]; then
 			# Non-fatal, continue.
 			printf '%s\n' "[SKIPPING] Filter not found. Please check configuration." | log
 			continue 1
 		fi
 
 		local i
-		for i in "generic" "generic:${_login}" "$filter_name"; do
+		for i in "generic" "generic:${_src_login}" "$_filter"; do
 			if [ -f "$BASE/config/filters/$i" ]; then
+				printf "%s\n" "Including filter \"$i\"" | log
 				cat "$BASE/config/filters/$i" >> "$tmp_filter_file"
 			fi
 		done
@@ -169,9 +173,9 @@ backup_loop()
 		local output
 		local rsync_ret
 		# Everything ready and initialized!
-		# The following -e specification needs to be indented with spaces
-		# because rsync is crappy!
-		if [ "$_host" = "localhost" ]; then
+		# Local copy, leave out the network switches.
+		case "$backup_mode" in
+		filecopy)
 			rsync \
 				$rsync_opts \
 				-a \
@@ -180,9 +184,13 @@ backup_loop()
 				--numeric-ids \
 				--filter=". $tmp_filter_file" \
 				$rsync_last_backup_dir \
-				"/" \
-				"${new_dir}/" > "${TMPDIR}/rsync_output" 2>&1
-		else
+				"$_src_dir" \
+				"$_dst_dir/$date" > "${TMPDIR}/rsync_output" 2>&1
+			;;
+		# Network copy.
+		push|pull)
+			# The following -e specification needs to be indented with spaces
+			# because rsync is crappy!
 			rsync \
 				$rsync_opts \
 				-a -z \
@@ -193,20 +201,20 @@ backup_loop()
 				--numeric-ids \
 				--filter=". $tmp_filter_file" \
 				$rsync_last_backup_dir \
-				"${_login}:/" \
-				"${new_dir}/" > "${TMPDIR}/rsync_output" 2>&1
-		fi
+				"$rsync_src" \
+				"$rsync_dst" > "${TMPDIR}/rsync_output" 2>&1
+			;;
+		esac
 		rsync_ret=$?
-		local ret
 
 		# Acceptable (= clean) exit codes are: 0, 23 and 24
 		for ret in 0 23 24; do 
 			if [ "$ret" -eq "$rsync_ret" ]; then
 				task_successes=$((task_successes + 1))
 				if [ "$debug" = "YES" ]; then
-					printf '%s\n' "[SUCCESSFUL=${rsync_ret}] \"${_login}\": $filter_name" | log
+					printf '%s\n' "[SUCCESSFUL=${rsync_ret}] \"${_src_login}\": $_filter" | log
 				else
-					printf '%s\n' "[SUCCESFUL] \"${_login}\": $filter_name" | log
+					printf '%s\n' "[SUCCESFUL] \"${_src_login}\": $_filter" | log
 				fi
 				rm -f "${TMPDIR}/rsync_output"
 				continue 2
